USE school_database;

CREATE TABLE STUDENT
(Student_ID INT unique PRIMARY KEY, FName VARCHAR(255), LName VARCHAR(255), Major VARCHAR(255), AcademicYear DATE);

SELECT * from STUDENT;


CREATE TABLE INSTRUCTOR
(Instructor_ID INT UNIQUE PRIMARY KEY, FullName VARCHAR(255), Department VARCHAR(255));
ALTER TABLE INSTRUCTOR RENAME COLUMN FullName TO Full_Name;
select * from INSTRUCTOR;

CREATE TABLE COURSE
(Course_ID INT UNIQUE PRIMARY KEY, Course_Title VARCHAR(255), Instructor INT,
CONSTRAINT fk_instructor_id FOREIGN KEY (Instructor) REFERENCES INSTRUCTOR(Instructor_ID)
);

SELECT * FROM COURSE;
ALTER TABLE COURSE RENAME COLUMN Instructor TO Instructor_ID;

CREATE TABLE ENROLLMENT
(
Enrollment_ID INT UNIQUE PRIMARY KEY, Student_ID INT, Course_ID INT,
CONSTRAINT fk_student_id FOREIGN KEY (Student_ID) REFERENCES STUDENT(Student_ID),
CONSTRAINT fk_course_id FOREIGN KEY (Course_ID) REFERENCES COURSE(Course_ID)
);

SELECT * FROM COURSE;