USE school_database;
-- STUDENT Table

CREATE TABLE STUDENT
(Student_ID INT unique PRIMARY KEY, FName VARCHAR(255), LName VARCHAR(255), Major VARCHAR(255), AcademicYear DATE);

SELECT * from STUDENT;
DESCRIBE STUDENT;

-- INSTRUCTOR Table
CREATE TABLE INSTRUCTOR
(Instructor_ID INT UNIQUE PRIMARY KEY, FullName VARCHAR(255), Department VARCHAR(255));
-- Rename the full-name column
ALTER TABLE INSTRUCTOR RENAME COLUMN FullName TO Full_Name;

select * from INSTRUCTOR;
DESCRIBE INSTRUCTOR;

-- COURSE Table
CREATE TABLE COURSE
(Course_ID INT UNIQUE PRIMARY KEY, Course_Title VARCHAR(255), Instructor INT,
CONSTRAINT fk_instructor_id FOREIGN KEY (Instructor) REFERENCES INSTRUCTOR(Instructor_ID)
);
-- Rename the Instructor column to Instructor_ID
ALTER TABLE COURSE RENAME COLUMN Instructor TO Instructor_ID;
SELECT * FROM COURSE;
DESCRIBE COURSE;

-- ENROLLMENT Table
CREATE TABLE ENROLLMENT
(Enrollment_ID INT UNIQUE PRIMARY KEY, Student_ID INT, Course_ID INT,
CONSTRAINT fk_student_id FOREIGN KEY (Student_ID) REFERENCES STUDENT(Student_ID),
CONSTRAINT fk_course_id FOREIGN KEY (Course_ID) REFERENCES COURSE(Course_ID)
);
-- ADD A GRADE COLUMN 
ALTER TABLE ENROLLMENT ADD COLUMN Grade CHAR(5);
SELECT * FROM ENROLLMENT;
DESCRIBE ENROLLMENT;

-- SHOW ALL TABLES
show tables;

